<?php

namespace app\components;

use yii\base\Widget;

class HelloWidget extends Widget
{
    public $name;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->name === null) {
            $this->name = 'Гость!';
        }
    }

    public function run()
    {
        return 'Привет' . $this->name;
    }
}